# Sandbox to run any code you want :)

---
## Setup

In [1]:
# Jax configuration
USE_JIT = True
USE_X64 = True
DEBUG_NANS = False
VERBOSE = False

In [2]:
# Standard library imports
import os
os.environ['JAX_ENABLE_X64'] = str(USE_X64).lower()

import logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

In [3]:
# Third party
import jax
jax.config.update("jax_disable_jit", not USE_JIT)
jax.config.update("jax_debug_nans", DEBUG_NANS)

from jax import jit, vmap
from jax.tree_util import register_pytree_node_class
import jax.numpy as jnp
import jax.scipy as jsp
from jax.lax import cond

import pandas as pd
import numpy as np

In [4]:
# Local imports
from Kernax import SEMagmaKernel, DiagKernel, ExpKernel, RBFKernel
from MagmaClustPy.hyperpost import hyperpost
from MagmaClustPy.hp_optimisation import optimise_hyperparameters
from MagmaClustPy.utils import preprocess_db
from MagmaClustPy.linalg import cho_factor, cho_solve, compute_mapping

INFO:2025-07-23 15:57:46,992:jax._src.xla_bridge:752: Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: dlopen(libtpu.so, 0x0001): tried: 'libtpu.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtpu.so' (no such file), '/opt/anaconda3/envs/MagmaClustPy/bin/../lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache), 'libtpu.so' (no such file)
2025-07-23 15:57:46,992 - INFO - Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: dlopen(libtpu.so, 0x0001): tried: 'libtpu.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtpu.so' (no such file), '/opt/anaconda3/envs/MagmaClustPy/bin/../lib/libtpu.so' (no such file), '/usr/lib/libtpu.so' (no such file, not in dyld cache), 'libtpu.so' (no such file)


In [5]:
# Config
key = jax.random.PRNGKey(42)
test_db_size = "small"

---
## Data

In [6]:
mean_kern = SEMagmaKernel(length_scale=jnp.array(0.3), variance=jnp.array(.2))
task_kern = SEMagmaKernel(length_scale=jnp.array(.5), variance=jnp.array(1.)) + DiagKernel(
			ExpKernel(jnp.array(-2.5)))

In [7]:
inputs = jnp.array([[[1.], [jnp.nan], [3]], [[1], [2], [3]]])
outputs = jnp.array([[[10.], [jnp.nan], [7]], [[11], [8], [6]]])
all_inputs = jnp.array([[1., 2, 3]]).T
mappings_on_all_inputs = vmap(compute_mapping, in_axes=(None, 0))(all_inputs, inputs)


grid = jnp.array([[1., 2, 3, 3.001,]]).T  # <- THIS
mappings_on_grid = vmap(compute_mapping, in_axes=(None, 0))(grid, inputs)

inputs.shape, outputs.shape, mappings_on_all_inputs.shape, all_inputs.shape, mappings_on_grid.shape, grid.shape

((2, 3, 1), (2, 3, 1), (2, 3), (3, 1), (2, 3), (4, 1))

In [8]:
hyperpost(inputs, outputs, mappings_on_all_inputs, all_inputs, jnp.array(0), mean_kern, task_kern)[0]

Array([4.82097502, 3.84135133, 2.87490429], dtype=float64)

In [9]:
hyperpost(inputs, outputs, mappings_on_grid, grid, jnp.array(0), mean_kern, task_kern)[0]

Array([4.82097502, 3.84135131, 2.87490427, 2.87412926], dtype=float64)

---
## Sandbox

In [10]:
mean_cov_on_all_inputs = mean_kern(all_inputs)
np.asarray(mean_cov_on_all_inputs)

array([[1.22140276, 0.84331974, 0.27758268],
       [0.84331974, 1.22140276, 0.84331974],
       [0.27758268, 0.84331974, 1.22140276]])

In [11]:
mean_cov_on_all_inputs_inv = cho_solve(cho_factor(mean_cov_on_all_inputs), jnp.eye(mean_cov_on_all_inputs.shape[0]))
np.asarray(mean_cov_on_all_inputs_inv)

array([[ 2.02478864, -2.06448768,  0.96526468],
       [-2.06448768,  3.6695892 , -2.06448768],
       [ 0.96526468, -2.06448768,  2.02478864]])

In [12]:
mean_cov_on_grid = mean_kern(grid)
np.asarray(mean_cov_on_grid)

array([[1.22140276, 0.84331974, 0.27758268, 0.27717161],
       [0.84331974, 1.22140276, 0.84331974, 0.84269491],
       [0.27758268, 0.84331974, 1.22140276, 1.22140231],
       [0.27717161, 0.84269491, 1.22140231, 1.22140276]])

In [13]:
mean_cov_on_grid_inv = cho_solve(cho_factor(mean_cov_on_grid), jnp.eye(grid.shape[0]))
np.asarray(mean_cov_on_grid_inv)

array([[ 3.01343481e+00, -5.18560905e+00,  2.16546458e+03,
        -2.16256984e+03],
       [-5.18560905e+00,  1.35228602e+01, -6.83531312e+03,
         6.82715733e+03],
       [ 2.16546458e+03, -6.83531312e+03,  4.73886356e+06,
        -4.73463721e+06],
       [-2.16256984e+03,  6.82715733e+03, -4.73463721e+06,
         4.73041666e+06]])

In [14]:
0/0

ZeroDivisionError: division by zero

In [ ]:
task_cov_no_grid = task_kern(inputs)

In [ ]:
np.asarray(task_cov_no_grid[0])

In [ ]:
np.asarray(task_cov_no_grid[1])

---

---