# Benchmarks - Likelihoods

**Main considerations when implementing Likelihoods**
- must be efficient, as they are used in the main bottleneck of the code: HP optimisation
- must work for both shared and distinct HPs

---
## Setup

In [1]:
# Standard library
import os

from MagmaClustPy.likelihoods import magma_neg_likelihood_on_cov

os.environ['JAX_ENABLE_X64'] = "True"

In [2]:
# Third party
import jax
import jax.numpy as jnp
from jax import jit, vmap
from jax.scipy.linalg import cho_factor, cho_solve
from jax.scipy.stats.multivariate_normal import logpdf

import pandas as pd
import numpy as np

In [3]:
# Local
from MagmaClustPy.hyperpost import hyperpost
from Kernax import SEMagmaKernel, NoisySEMagmaKernel
from MagmaClustPy.utils import preprocess_db

In [4]:
# Config
nugget=jnp.array(1e-4)

---
## Data

In [5]:
test_db_size = "medium"
key = jax.random.PRNGKey(42)

---
## Current implementation

In [6]:
import MagmaClustPy

magma_neg_likelihood_old = MagmaClustPy.likelihoods.magma_neg_likelihood
magma_neg_likelihood_on_cov_old = MagmaClustPy.likelihoods.magma_neg_likelihood_on_cov

---
## Custom implementation(s)

In [7]:
import jax.numpy as jnp
from jax import jit, vmap
from jax.scipy.stats.multivariate_normal import logpdf

from MagmaClustPy.linalg import extract_from_full_array, extract_from_full_matrix, solve_right_cholesky


@jit
def magma_neg_likelihood_on_cov(covar, outputs, mean, mean_process_cov, mapping, nugget=jnp.array(1e-10)):
	outputs = outputs.ravel()  # For multi-output, we want to flatten the outputs.
	mean = mean.ravel()  # As the goal of likelihood is to see if the mean is close to the outputs, we want to flatten it too.

	nugget_matrix = jnp.eye(outputs.shape[0]) * nugget

	eyed_covar = jnp.where(jnp.isnan(covar), jnp.eye(covar.shape[0]), covar)
	zeroed_outputs = jnp.nan_to_num(outputs)
	if mapping is not None:
		zeroed_mean = jnp.nan_to_num(extract_from_full_array(mean, outputs, mapping))
		eyed_mean_cov = jnp.where(jnp.isnan(covar), jnp.eye(covar.shape[0]), extract_from_full_matrix(mean_process_cov, outputs, mapping))
	else:
		zeroed_mean = jnp.nan_to_num(mean)
		eyed_mean_cov = jnp.where(jnp.isnan(covar), jnp.eye(covar.shape[0]), mean_process_cov)


	# Compute log-likelihood
	multiv_neg_log_lik = -logpdf(zeroed_outputs, zeroed_mean, eyed_covar + nugget_matrix)

	# Compute correction term
	correction = 0.5 * jnp.trace(solve_right_cholesky(eyed_covar, eyed_mean_cov, nugget=nugget))

	# Compute padding corrections
	# The logpdf is computed as:
	# -0.5 * (N * log(2 * pi) + log(det(cov)) + (outputs - mean).T @ inv(cov) @ (outputs - mean))
	# det(cov) and the Mahalanobis distance are not affected by our padding
	# We only have to correct for the -0.5 * N * log(2 * pi) term, as N is bigger with padding
	nll_pad_correction = 0.5 * jnp.log(2 * jnp.pi) * jnp.sum(jnp.isnan(outputs))

	# We also need to correct the correction term, as padding adds 1s to the diagonal and hence 1 to the trace
	corr_pad_correction = 0.5 * jnp.sum(jnp.isnan(outputs))

	return (multiv_neg_log_lik - nll_pad_correction) + (correction - corr_pad_correction)


@jit
def magma_neg_likelihood(kernel, inputs, outputs: jnp.array, mean: jnp.array, mean_process_cov: jnp.array, mappings: jnp.array, nugget=jnp.array(1e-10)):
	"""
	Computes the MAGMA log-likelihood.

	:param kernel: the kernel containing HPs to optimise. This kernel is used to compute the covariance (matrix `S`)
	:param inputs: inputs on which to compute the covariance matrix (shape (N, ))
	:param mask: boolean masks indicating which inputs and outputs to consider (shape (N, ))  #TODO: fix
	:param outputs: the observed values (shape (N, ))
	:param mean: the mean over the inputs (scalar or vector of shape (N, ))
	:param mean_process_cov: the hypper-posterior mean process covariance (matrix K^t)
	:param nugget: the nugget, for numerical stability

	:return: the negative log-likelihood (scalar)
	"""
	# In multi-output, we want to flatten the outputs.
	# The user should provide a specific Kernel to compute a cross-covariance with the right shape too
	outputs = outputs.reshape(outputs.shape[0], -1)

	if mean.ndim == 0:
		mean = jnp.broadcast_to(mean[None], outputs.shape)

	covar = kernel(inputs)

	# check if we need to vmap
	if inputs.ndim == 2:
		return magma_neg_likelihood_on_cov(covar, outputs, mean, mean_process_cov, mappings, nugget)
	elif inputs.ndim == 3:
		return vmap(magma_neg_likelihood_on_cov, in_axes=(0, 0, None, None, 0, None))(covar, outputs, mean, mean_process_cov, mappings, nugget)
	else:
		raise ValueError("inputs must be either 1D or 2D")

In [8]:
magma_neg_likelihood_new = magma_neg_likelihood
magma_neg_likelihood_on_cov_new = magma_neg_likelihood_on_cov

---
## Comparison

### Sample test

In [9]:
db = pd.DataFrame({
	'Task_ID': [1, 1, 1, 1, 2, 2, 2, 2],
	'Input': [0.40, 4.45, 7.60, 8.30, 3.50, 5.10, 8.85, 9.35],
	'Input_ID': ['x', 'x', 'x', 'x', 'x', 'x', 'x', 'x'],
	'Output': [59.81620, 67.13694, 78.32495, 81.83590, 62.04943, 67.31932, 85.94063, 86.76426],
	'Output_ID': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'],
})

padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)

prior_mean = jnp.array(0)
all_inputs.shape, padded_inputs.shape

((8, 1), (2, 4, 1))

In [10]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)
task_kern = NoisySEMagmaKernel(length_scale=.3, variance=1., noise=2.5)

In [11]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, prior_mean, mean_kern, task_kern, all_inputs=all_inputs, nugget=nugget)
post_mean.shape, post_cov.shape

((8,), (8, 8))

In [12]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, jnp.full(all_inputs.squeeze().shape, prior_mean), post_cov, None, nugget=nugget)
mean_llh_old.item()

1784.2900390625

In [13]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget)
mean_llh_new.item()

1784.2900390625

In [14]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [15]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

9.25 μs ± 195 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [16]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

10.3 μs ± 661 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [17]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_old)

array([ 979.3764, 1425.9928], dtype=float32)

In [18]:
task_llhs_new = magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_new)

array([ 979.3764, 1425.9928], dtype=float32)

In [19]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [20]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

58.9 μs ± 3.21 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [21]:
%timeit magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

49.7 μs ± 1.03 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### shared Input, shared HP

In [22]:
db = pd.read_csv(f"../datasets/{test_db_size}_shared_input_shared_hp.csv")

padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)

prior_mean = jnp.array(0)
all_inputs.shape, padded_inputs.shape

((150, 1), (200, 150, 1))

In [23]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)
task_kern = NoisySEMagmaKernel(length_scale=.3, variance=1., noise=2.5)

In [24]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, prior_mean, mean_kern, task_kern, all_inputs=all_inputs, nugget=nugget)
post_mean.shape, post_cov.shape

((150,), (150, 150))

In [25]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, jnp.full(all_inputs.squeeze().shape, prior_mean), post_cov, None, nugget=nugget)
mean_llh_old.item()

872167.75

In [26]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget)
mean_llh_new.item()

872167.75

In [27]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [28]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

263 μs ± 7.15 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [29]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

261 μs ± 5.55 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [30]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_old)

array([443.60623, 454.33514, 457.4909 , 455.43054, 462.82095, 463.07523,
       455.4749 , 455.17505, 445.59637, 448.59924, 454.36047, 455.02356,
       452.37225, 458.5221 , 466.32495, 443.44504, 446.11185, 461.92776,
       450.13547, 459.11014, 457.8158 , 447.38824, 453.94556, 447.88974,
       447.32092, 458.37628, 452.34546, 453.8296 , 458.3998 , 441.71176,
       444.6034 , 446.18707, 448.72382, 445.65454, 439.13727, 453.74615,
       465.72504, 457.96024, 461.77377, 464.66547, 453.10135, 460.84247,
       454.2546 , 446.46265, 458.79422, 455.19415, 447.37918, 463.7545 ,
       454.7738 , 450.6353 , 448.41592, 465.51456, 463.16537, 445.1893 ,
       460.41043, 454.84998, 448.88474, 455.19244, 445.32806, 469.64545,
       459.3202 , 463.84857, 456.37054, 460.3284 , 457.97467, 432.5199 ,
       447.77032, 458.05536, 446.3839 , 436.29736, 470.28336, 449.6275 ,
       455.74258, 454.30447, 460.1877 , 442.18527, 455.8119 , 456.85345,
       458.8584 , 460.14972, 456.49634, 452.11597, 

In [31]:
task_llhs_new = magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_new)

array([443.60623, 454.33514, 457.4909 , 455.43054, 462.82095, 463.07523,
       455.4749 , 455.17505, 445.59637, 448.59924, 454.36047, 455.02356,
       452.37225, 458.5221 , 466.32495, 443.44504, 446.11185, 461.92776,
       450.13547, 459.11014, 457.8158 , 447.38824, 453.94556, 447.88974,
       447.32092, 458.37628, 452.34546, 453.8296 , 458.3998 , 441.71176,
       444.6034 , 446.18707, 448.72382, 445.65454, 439.13727, 453.74615,
       465.72504, 457.96024, 461.77377, 464.66547, 453.10135, 460.84247,
       454.2546 , 446.46265, 458.79422, 455.19415, 447.37918, 463.7545 ,
       454.7738 , 450.6353 , 448.41592, 465.51456, 463.16537, 445.1893 ,
       460.41043, 454.84998, 448.88474, 455.19244, 445.32806, 469.64545,
       459.3202 , 463.84857, 456.37054, 460.3284 , 457.97467, 432.5199 ,
       447.77032, 458.05536, 446.3839 , 436.29736, 470.28336, 449.6275 ,
       455.74258, 454.30447, 460.1877 , 442.18527, 455.8119 , 456.85345,
       458.8584 , 460.14972, 456.49634, 452.11597, 

In [32]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [33]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

21.3 ms ± 287 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [34]:
%timeit magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

21.9 ms ± 507 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### shared Input, Distinct HP

In [35]:
db = pd.read_csv(f"../datasets/{test_db_size}_shared_input_distinct_hp.csv")

padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)

prior_mean = jnp.array(0)
all_inputs.shape, padded_inputs.shape

((150, 1), (200, 150, 1))

In [38]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)

key, subkey = jax.random.split(key)
distinct_length_scales = jax.random.uniform(subkey, (padded_outputs.shape[0],), jnp.float64, .1, 1)
task_kern = NoisySEMagmaKernel(length_scale=distinct_length_scales, variance=1., noise=2.5)

/var/folders/93/wvvdyy810s1cvn67rnn9x0jh0000gn/T/ipykernel_42647/3792235761.py:4: UserWarning: Explicitly requested dtype <class 'jax.numpy.float64'>  is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  distinct_length_scales = jax.random.uniform(subkey, (padded_outputs.shape[0],), jnp.float64, .1, 1)


In [39]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, prior_mean, mean_kern, task_kern, all_inputs=all_inputs, nugget=nugget)
post_mean.shape, post_cov.shape

((150,), (150, 150))

In [40]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, jnp.full(all_inputs.squeeze().shape, prior_mean), post_cov, None, nugget=nugget)
mean_llh_old.item()

10184.91015625

In [41]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget)
mean_llh_new.item()

10184.91015625

In [42]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [43]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

275 μs ± 7.99 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [44]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

278 μs ± 39.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [45]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_old)

array([368.46924, 350.73856, 383.92505, 354.0627 , 378.3974 , 358.28143,
       356.79285, 352.79968, 352.25452, 372.72284, 359.9822 , 354.92197,
       376.4286 , 354.17523, 357.2848 , 357.3538 , 365.78497, 358.9017 ,
       367.76785, 366.73138, 350.813  , 355.27225, 356.43472, 363.19025,
       358.97113, 355.15176, 367.43173, 363.86935, 354.03308, 351.23694,
       370.45346, 355.0303 , 360.4977 , 363.8922 , 356.56998, 357.88254,
       362.8017 , 365.79617, 352.51248, 360.95514, 354.53955, 352.40512,
       351.99002, 353.7372 , 360.19653, 357.71985, 358.43665, 352.18396,
       362.94357, 359.8821 , 359.80106, 358.2188 , 358.11472, 360.6475 ,
       359.09424, 365.81097, 350.82513, 361.59485, 363.24628, 355.84955,
       355.28027, 372.99246, 357.635  , 357.41534, 356.809  , 367.62555,
       358.13132, 353.96695, 372.76688, 351.66638, 362.16776, 375.04776,
       355.6978 , 350.76492, 366.0428 , 358.63593, 361.47427, 359.33038,
       370.81058, 376.66232, 357.37097, 361.47787, 

In [46]:
task_llhs_new = magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_new)

array([368.46924, 350.73856, 383.92505, 354.0627 , 378.3974 , 358.28143,
       356.79285, 352.79968, 352.25452, 372.72284, 359.9822 , 354.92197,
       376.4286 , 354.17523, 357.2848 , 357.3538 , 365.78497, 358.9017 ,
       367.76785, 366.73138, 350.813  , 355.27225, 356.43472, 363.19025,
       358.97113, 355.15176, 367.43173, 363.86935, 354.03308, 351.23694,
       370.45346, 355.0303 , 360.4977 , 363.8922 , 356.56998, 357.88254,
       362.8017 , 365.79617, 352.51248, 360.95514, 354.53955, 352.40512,
       351.99002, 353.7372 , 360.19653, 357.71985, 358.43665, 352.18396,
       362.94357, 359.8821 , 359.80106, 358.2188 , 358.11472, 360.6475 ,
       359.09424, 365.81097, 350.82513, 361.59485, 363.24628, 355.84955,
       355.28027, 372.99246, 357.635  , 357.41534, 356.809  , 367.62555,
       358.13132, 353.96695, 372.76688, 351.66638, 362.16776, 375.04776,
       355.6978 , 350.76492, 366.0428 , 358.63593, 361.47427, 359.33038,
       370.81058, 376.66232, 357.37097, 361.47787, 

In [47]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [48]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

21.3 ms ± 315 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [49]:
%timeit magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

21.1 ms ± 374 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Distinct Input, shared HP

In [50]:
db = pd.read_csv(f"../datasets/{test_db_size}_distinct_input_shared_hp.csv")

padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)

prior_mean = jnp.array(0)
all_inputs.shape, padded_inputs.shape

((401, 1), (200, 190, 1))

In [51]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)
task_kern = NoisySEMagmaKernel(length_scale=.6, variance=1., noise=2.5)

In [52]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, prior_mean, mean_kern, task_kern, all_inputs=all_inputs, nugget=nugget)
post_mean.shape, post_cov.shape

((401,), (401, 401))

In [54]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, jnp.full(all_inputs.squeeze().shape, prior_mean), post_cov, None, nugget=nugget)
mean_llh_old.item()

inf

In [55]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget)
mean_llh_new.item()

inf

In [56]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [57]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

1.09 ms ± 32.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [58]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

1.24 ms ± 92.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [59]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_old)

array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, in

In [60]:
task_llhs_new = magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_new)

array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, in

In [61]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [62]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

32.4 ms ± 330 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [63]:
%timeit magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

31.9 ms ± 581 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Distinct Input, Distinct HP

In [64]:
db = pd.read_csv(f"../datasets/{test_db_size}_distinct_input_distinct_hp.csv")

padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)

prior_mean = jnp.array(0)
all_inputs.shape, padded_inputs.shape

((401, 1), (200, 188, 1))

In [67]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)

key, subkey = jax.random.split(key)
distinct_length_scales = jax.random.uniform(subkey, (padded_outputs.shape[0],), jnp.float32, .1, 1)
task_kern = NoisySEMagmaKernel(length_scale=distinct_length_scales, variance=1., noise=2.5)

In [68]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, prior_mean, mean_kern, task_kern, all_inputs=all_inputs, nugget=nugget)
post_mean.shape, post_cov.shape

((401,), (401, 401))

In [69]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, jnp.full(all_inputs.squeeze().shape, prior_mean), post_cov, None, nugget=nugget)
mean_llh_old.item()

inf

In [70]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget)
mean_llh_new.item()

inf

In [71]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [72]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

1.07 ms ± 22.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [73]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean, post_cov, None, nugget=nugget).block_until_ready()

1.15 ms ± 34.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [74]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_old)

array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, in

In [75]:
task_llhs_new = magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)
np.asarray(task_llhs_new)

array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, in

In [76]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [77]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs.squeeze(), post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

30.8 ms ± 342 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [78]:
%timeit magma_neg_likelihood_new(task_kern, padded_inputs, padded_outputs, post_mean, post_cov, mappings, nugget=nugget)[0].block_until_ready()

31.6 ms ± 896 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


---