# Benchmarks - Likelihoods

**Main considerations when implementing Likelihoods**
- must be efficient, as they are used in the main bottleneck of the code: HP optimisation
- must work for both shared and distinct HPs

---
## Setup

In [147]:
# Jax configuration
USE_JIT = True
USE_X64 = True
DEBUG_NANS = False
VERBOSE = False

In [148]:
# Standard library imports
import os
os.environ['JAX_ENABLE_X64'] = str(USE_X64).lower()

import logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

In [149]:
# Third party
import jax
jax.config.update("jax_disable_jit", not USE_JIT)
jax.config.update("jax_debug_nans", DEBUG_NANS)

from jax import vmap
import jax.numpy as jnp
import jax.random as jrd
from kernax import DiagKernel, ExpKernel, BatchKernel, AbstractKernel

import pandas as pd
import numpy as np

In [150]:
# Local
from MagmaClustPy.utils import preprocess_db
from MagmaClustPy.hyperpost import hyperpost
from MagmaClustPy.custom_kernels import SEMagmaKernel
from MagmaClustPy.initialisation import k_means_init

In [151]:
# Config
key = jrd.PRNGKey(0)
test_db_size = "small"
nb_cluster = 4
jitter = jnp.array(1e-5)

---
## Data

---
## Current implementation

In [152]:
import MagmaClustPy

magma_neg_likelihood_old = MagmaClustPy.likelihoods.magma_neg_likelihood
magma_neg_likelihood_on_cov_old = MagmaClustPy.likelihoods.magma_neg_likelihood_on_cov

---
## Custom implementation(s)

*Start by copy-pasting the original function from the MagmaClustPy module, then bring modifications*

We wish to change the API !

* `magma_neg_likelihood_on_cov` should become `magma_neg_likelihood`, and receive the kernel directly, and work at the single-task scale only
* depending on the use, we might call it inside various `vmap`s in `optimise_[...]` methods
* This eliminates a useless intermediary function

In [153]:
from typing import Optional, Union

import jax.numpy as jnp
from jax import jit, vmap, Array
from jax.scipy.stats.multivariate_normal import logpdf
from kernax import AbstractKernel

from MagmaClustPy.linalg import extract_from_full_array, extract_from_full_matrix, solve_right_cholesky


@jit
def magma_neg_likelihood(kernel: AbstractKernel, inputs: Array, outputs: Array, mean: Array,
                         mean_process_cov: Array, mappings: Optional[Array],
                         jitter: Optional[Array] = jnp.array(1e-10)) -> Array:
	"""
	Computes the Magma Negative Log Likelihood for a given sequence of points and covariance kernel, relative to a posterior mean and covariance.

	:param kernel: A kernel to compute the covariance on inputs
	:param inputs: The inputs from one task. Shape: (Max_N_i, D)
	:param outputs: The outputs from one task, corresponding to the inputs. Shape: (Max_N_i, D)
	:param mean: The posterior mean to which the outputs are compared. Shape (N, D)
	:param mean_process_cov: The posterior covariance matrix to which the task covariance is compared. Shape (N, N)
	:param mappings: The mappings from input points (in 0..Max_N_i) to full grid (0..N). Shape (Max_N_i, )
	:param jitter: The jitter to use. Scalar.

	:return: The negative log-likelihood with the magma correction term. Scalar.
	"""
	outputs = outputs.ravel()  # For multi-output, we want to flatten the outputs.
	mean = mean.ravel()  # As the goal of likelihood is to see if the mean is close to the outputs, we want to flatten
	# it too.

	jitter_matrix = jnp.eye(outputs.shape[0]) * jitter

	cov = kernel(inputs)

	eyed_cov = jnp.where(jnp.isnan(cov), jnp.eye(cov.shape[0]), cov)
	zeroed_outputs = jnp.nan_to_num(outputs)
	if mappings is not None:
		zeroed_mean = jnp.nan_to_num(extract_from_full_array(mean, outputs, mappings))
		eyed_mean_cov = jnp.where(jnp.isnan(cov), jnp.eye(cov.shape[0]),
		                          extract_from_full_matrix(mean_process_cov, outputs, mappings))
	else:
		zeroed_mean = jnp.nan_to_num(mean)
		eyed_mean_cov = jnp.where(jnp.isnan(cov), jnp.eye(cov.shape[0]), mean_process_cov)

	# Compute log-likelihood
	multiv_neg_log_lik = -logpdf(zeroed_outputs, zeroed_mean, eyed_cov + jitter_matrix)

	# Compute correction term
	correction = 0.5 * jnp.trace(solve_right_cholesky(eyed_cov, eyed_mean_cov, jitter=jitter))

	# Compute padding corrections
	# The logpdf is computed as:
	# -0.5 * (N * log(2 * pi) + log(det(cov)) + (outputs - mean).T @ inv(cov) @ (outputs - mean))
	# det(cov) and the Mahalanobis distance are not affected by our padding
	# We only have to correct for the -0.5 * N * log(2 * pi) term, as N is bigger with padding
	nll_pad_correction = 0.5 * jnp.log(2 * jnp.pi) * jnp.sum(jnp.isnan(outputs))

	# We also need to correct the correction term, as padding adds 1s to the diagonal and hence 1 to the trace
	corr_pad_correction = 0.5 * jnp.sum(jnp.isnan(outputs))

	return (multiv_neg_log_lik - nll_pad_correction) + (correction - corr_pad_correction)

"""
@jit
def magma_neg_likelihood(kernel, inputs: jnp.ndarray, outputs: jnp.ndarray, mappings: Optional[jnp.ndarray],
                         mean: jnp.ndarray,
                         mean_process_cov: jnp.ndarray, jitter: jnp.ndarray = jnp.array(1e-10)) -> Union[
	jnp.ndarray, float]:

	Computes the MAGMA negative log-likelihood.

	:param kernel: The kernel to optimise. This kernel is used to compute the covariance (matrix `S`).
	:param inputs: Inputs on which to compute the covariance matrix (shape (N, I)) or (T, Max_N_i, I).
	:param outputs: The observed values for each input (shape (N, O) or (T, Max_N_i, O)).
	:param mappings: The indices of the inputs in the all_inputs array, if we compute the likelihood on a batch of
	:param mean: The mean over the inputs (scalar or vector of shape (N,)).
	:param mean_process_cov: The hyperpost mean process covariance (matrix K^t)
	inputs. Shape (T, Max_N_i)
	:param jitter: jitter term to ensure numerical stability. Default is 1e-10

	:return: The negative log-likelihood (scalar or (T, ))

	# In multi-output, we want to flatten the outputs.
	# The user should provide a specific Kernel to compute a cross-covariance with the right shape too
	outputs = outputs.reshape(outputs.shape[0], -1)

	if mean.ndim == 0:
		mean = jnp.broadcast_to(mean[None], outputs.shape)

	covar = kernel(inputs)

	# check if we need to vmap
	if inputs.ndim == 2:
		return magma_neg_likelihood_on_cov(covar, outputs, mean, mean_process_cov, mappings, jitter)
	elif inputs.ndim == 3:
		return vmap(magma_neg_likelihood_on_cov, in_axes=(0, 0, None, None, 0, None))(covar, outputs, mean,
		                                                                              mean_process_cov, mappings,
		                                                                              jitter)
	else:
		raise ValueError("inputs must be either 1D or 2D")
"""


'\n@jit\ndef magma_neg_likelihood(kernel, inputs: jnp.ndarray, outputs: jnp.ndarray, mappings: Optional[jnp.ndarray],\n                         mean: jnp.ndarray,\n                         mean_process_cov: jnp.ndarray, jitter: jnp.ndarray = jnp.array(1e-10)) -> Union[\n\tjnp.ndarray, float]:\n\n\tComputes the MAGMA negative log-likelihood.\n\n\t:param kernel: The kernel to optimise. This kernel is used to compute the covariance (matrix `S`).\n\t:param inputs: Inputs on which to compute the covariance matrix (shape (N, I)) or (T, Max_N_i, I).\n\t:param outputs: The observed values for each input (shape (N, O) or (T, Max_N_i, O)).\n\t:param mappings: The indices of the inputs in the all_inputs array, if we compute the likelihood on a batch of\n\t:param mean: The mean over the inputs (scalar or vector of shape (N,)).\n\t:param mean_process_cov: The hyperpost mean process covariance (matrix K^t)\n\tinputs. Shape (T, Max_N_i)\n\t:param jitter: jitter term to ensure numerical stability. Def

In [154]:
magma_neg_likelihood_new = magma_neg_likelihood
#magma_neg_likelihood_on_cov_new = magma_neg_likelihood_on_cov

---
## Comparison

### Minimal test scenario

In [155]:
db = pd.DataFrame({
	'Task_ID': [1, 1, 1, 1, 2, 2, 2, 2],
	'Input': [0.40, 4.45, 7.60, 8.30, 3.50, 5.10, 8.85, 9.35],
	'Input_ID': ['x', 'x', 'x', 'x', 'x', 'x', 'x', 'x'],
	'Output': [59.81620, 67.13694, 78.32495, 81.83590, 62.04943, 67.31932, 85.94063, 86.76426],
	'Output_ID': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'],
})

padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)
prior_mean = jnp.array(0)
prior_mean_on_grid = jnp.full(all_inputs.squeeze().shape, 0)

all_inputs.shape, padded_inputs.shape

((8, 1), (2, 4, 1))

In [156]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)
task_kern = SEMagmaKernel(length_scale=.3, variance=1.) + DiagKernel(ExpKernel(2.5))
task_kern = BatchKernel(task_kern, batch_size=padded_inputs.shape[0], batch_in_axes=None, batch_over_inputs=True)

In [157]:
shared_input = len(padded_inputs[0]) == len(all_inputs) and not jnp.any(jnp.isnan(padded_inputs))
shared_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.batch_in_axes))
shared_input, shared_hp

(False, True)

In [158]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, all_inputs, prior_mean, mean_kern, task_kern, shared_input, shared_hp)
post_mean.shape, post_cov.shape

((8,), (8, 8))

In [159]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter)
mean_llh_old.item()

287.7354352573187

In [160]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter)
mean_llh_new.item()

287.7354352573187

In [161]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [162]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter).block_until_ready()

11.9 μs ± 777 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [163]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter).block_until_ready()

11.4 μs ± 351 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [164]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)
np.asarray(task_llhs_old)

array([328.64376795, 342.88664196])

In [165]:
batched_magma_neg_likelihood = vmap(magma_neg_likelihood_new, in_axes=(None, 0, 0, None, None, 0, None))
task_llhs_new = batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter)
np.asarray(task_llhs_new)

array([328.64376795, 342.88664196])

In [166]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [167]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter).block_until_ready()

33.9 μs ± 200 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [168]:
%timeit batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter).block_until_ready()

183 μs ± 528 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### Magma scenarios

#### Shared Input, Shared HP

In [169]:
db = pd.read_csv(f"../datasets/K=1/{test_db_size}_shared_input_shared_hp.csv")
padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)
prior_mean = jnp.array(0)
prior_mean_on_grid = jnp.full(all_inputs.squeeze().shape, 0)
all_inputs.shape, padded_inputs.shape

((15, 1), (20, 15, 1))

In [170]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)
task_kern = SEMagmaKernel(length_scale=.3, variance=1.) + DiagKernel(ExpKernel(2.5))
task_kern = BatchKernel(task_kern, batch_size=padded_inputs.shape[0], batch_in_axes=None, batch_over_inputs=True)

In [171]:
shared_input = len(padded_inputs[0]) == len(all_inputs) and not jnp.any(jnp.isnan(padded_inputs))
shared_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.batch_in_axes))
shared_input, shared_hp

(True, True)

In [172]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, all_inputs, jnp.array(0.), mean_kern, task_kern, shared_input, shared_hp)
post_mean.shape, post_cov.shape

((15,), (15, 15))

In [173]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter)
mean_llh_old.item()

836.6026400047816

In [174]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter)
mean_llh_new.item()

836.6026400047816

In [175]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [176]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter).block_until_ready()

24 μs ± 222 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [177]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter).block_until_ready()

23.5 μs ± 151 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [178]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)
np.asarray(task_llhs_old)

array([42.22463713, 40.37348383, 42.57813662, 47.13218903, 43.98828872,
       41.02506917, 41.88972722, 46.92292217, 47.88224903, 46.58550478,
       46.90791271, 47.04250563, 46.02066324, 38.94021312, 45.39700296,
       43.69319704, 46.18741578, 41.56356531, 46.66202691, 45.41861918])

In [179]:
batched_magma_neg_likelihood = vmap(magma_neg_likelihood_new, in_axes=(None, 0, 0, None, None, 0, None))
task_llhs_new = batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter)
np.asarray(task_llhs_new)

array([42.22463713, 40.37348383, 42.57813662, 47.13218903, 43.98828872,
       41.02506917, 41.88972722, 46.92292217, 47.88224903, 46.58550478,
       46.90791271, 47.04250563, 46.02066324, 38.94021312, 45.39700296,
       43.69319704, 46.18741578, 41.56356531, 46.66202691, 45.41861918])

In [180]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [181]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter).block_until_ready()

124 μs ± 354 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [182]:
%timeit batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter).block_until_ready()

259 μs ± 1.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Shared Input, Distinct HP

In [183]:
db = pd.read_csv(f"../datasets/K=1/{test_db_size}_shared_input_distinct_hp.csv")
padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)
prior_mean = jnp.array(0)
prior_mean_on_grid = jnp.full(all_inputs.squeeze().shape, 0)
all_inputs.shape, padded_inputs.shape

((15, 1), (20, 15, 1))

In [184]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)
task_kern = SEMagmaKernel(length_scale=.6, variance=1.) + DiagKernel(ExpKernel(2.5))
task_kern = BatchKernel(task_kern, batch_size=padded_inputs.shape[0], batch_in_axes=0, batch_over_inputs=True)

In [185]:
shared_input = len(padded_inputs[0]) == len(all_inputs) and not jnp.any(jnp.isnan(padded_inputs))
shared_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.batch_in_axes))

In [186]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, all_inputs, prior_mean, mean_kern, task_kern, shared_input, shared_hp)
post_mean.shape, post_cov.shape

((15,), (15, 15))

In [187]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter)
mean_llh_old.item()

1719.4996907302414

In [188]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter)
mean_llh_new.item()

1719.4996907302414

In [189]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [190]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter).block_until_ready()

23.9 μs ± 114 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [191]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter).block_until_ready()

23.9 μs ± 104 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [192]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)
np.asarray(task_llhs_old)

array([50.34739556, 54.23050344, 41.39021497, 53.95277976, 51.09525473,
       49.01916269, 47.49520364, 52.40114977, 56.94971548, 51.1446679 ,
       47.91762041, 56.19119473, 56.86190659, 48.42610193, 44.18702792,
       43.24161907, 57.63404576, 51.32569498, 53.69042879, 58.2424118 ])

In [193]:
batched_magma_neg_likelihood = vmap(magma_neg_likelihood_new, in_axes=(task_kern.batch_in_axes, 0, 0, None, None, 0, None))
task_llhs_new = batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter)
np.asarray(task_llhs_new)

array([50.34739556, 54.23050344, 41.39021497, 53.95277976, 51.09525473,
       49.01916269, 47.49520364, 52.40114977, 56.94971548, 51.1446679 ,
       47.91762041, 56.19119473, 56.86190659, 48.42610193, 44.18702792,
       43.24161907, 57.63404576, 51.32569498, 53.69042879, 58.2424118 ])

In [194]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [195]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter).block_until_ready()

124 μs ± 227 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [196]:
%timeit batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter).block_until_ready()

285 μs ± 2.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Distinct Input, shared HP

In [197]:
db = pd.read_csv(f"../datasets/K=1/{test_db_size}_distinct_input_shared_hp.csv")
padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)
prior_mean = jnp.array(0)
prior_mean_on_grid = jnp.full(all_inputs.squeeze().shape, 0)
all_inputs.shape, padded_inputs.shape

((41, 1), (20, 15, 1))

In [198]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)
task_kern = SEMagmaKernel(length_scale=.6, variance=1.) + DiagKernel(ExpKernel(2.5))
task_kern = BatchKernel(task_kern, batch_size=padded_inputs.shape[0], batch_in_axes=None, batch_over_inputs=True)

In [199]:
shared_input = len(padded_inputs[0]) == len(all_inputs) and not jnp.any(jnp.isnan(padded_inputs))
shared_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.batch_in_axes))

In [200]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, all_inputs, prior_mean, mean_kern, task_kern, shared_input, shared_hp)
post_mean.shape, post_cov.shape

((41,), (41, 41))

In [201]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter)
mean_llh_old.item()

1552.079251979369

In [202]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter)
mean_llh_new.item()

1552.079251979369

In [203]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [204]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter).block_until_ready()

138 μs ± 3.07 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [205]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter).block_until_ready()

130 μs ± 11.6 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [206]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)
np.asarray(task_llhs_old)

array([52.57362646, 46.72328894, 43.20750069, 52.81551319, 58.45067153,
       48.95918061, 44.91474505, 51.92632597, 43.71241903, 51.96189126,
       55.93982758, 72.01105581, 45.62851757, 46.88118758, 44.86650358,
       42.64239789, 57.16337493, 57.11251711, 46.84806571, 51.67676024])

In [207]:
batched_magma_neg_likelihood = vmap(magma_neg_likelihood_new, in_axes=(None, 0, 0, None, None, 0, None))
task_llhs_new = batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter)
np.asarray(task_llhs_new)

array([52.57362646, 46.72328894, 43.20750069, 52.81551319, 58.45067153,
       48.95918061, 44.91474505, 51.92632597, 43.71241903, 51.96189126,
       55.93982758, 72.01105581, 45.62851757, 46.88118758, 44.86650358,
       42.64239789, 57.16337493, 57.11251711, 46.84806571, 51.67676024])

In [208]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [209]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter).block_until_ready()

125 μs ± 449 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [210]:
%timeit batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter).block_until_ready()

264 μs ± 1.91 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Distinct Input, Distinct HP

In [211]:
db = pd.read_csv(f"../datasets/K=1/{test_db_size}_distinct_input_distinct_hp.csv")
padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)
prior_mean = jnp.array(0)
prior_mean_on_grid = jnp.full(all_inputs.squeeze().shape, 0)
all_inputs.shape, padded_inputs.shape

((41, 1), (20, 19, 1))

In [212]:
mean_kern = SEMagmaKernel(length_scale=.3, variance=1.)
task_kern = SEMagmaKernel(length_scale=.3, variance=1.) + DiagKernel(ExpKernel(2.5))
task_kern = BatchKernel(task_kern, batch_size=padded_inputs.shape[0], batch_in_axes=0, batch_over_inputs=True)

In [213]:
shared_input = len(padded_inputs[0]) == len(all_inputs) and not jnp.any(jnp.isnan(padded_inputs))
shared_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.batch_in_axes))

In [214]:
post_mean, post_cov = hyperpost(padded_inputs, padded_outputs, mappings, all_inputs, prior_mean, mean_kern, task_kern, shared_input, shared_hp)
post_mean.shape, post_cov.shape

((41,), (41, 41))

In [215]:
mean_llh_old = magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter)
mean_llh_old.item()

399.46935219657354

In [216]:
mean_llh_new = magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter)
mean_llh_new.item()

399.46935219657354

In [217]:
jnp.allclose(mean_llh_old, mean_llh_new)

Array(True, dtype=bool)

In [218]:
%timeit magma_neg_likelihood_old(mean_kern, all_inputs, post_mean, None, prior_mean_on_grid, post_cov, jitter=jitter).block_until_ready()

114 μs ± 5.46 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [219]:
%timeit magma_neg_likelihood_new(mean_kern, all_inputs, post_mean, prior_mean_on_grid, post_cov, mappings=None, jitter=jitter).block_until_ready()

113 μs ± 6.45 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [220]:
task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)
np.asarray(task_llhs_old)

array([47.36790518, 48.19434489, 50.82895179, 46.73893308, 58.35595581,
       53.97453623, 50.98050792, 46.6903078 , 49.99814406, 55.66992366,
       46.08494662, 53.17678346, 45.49733488, 54.75629848, 50.89977383,
       50.36314154, 57.20056399, 51.89880572, 52.64762765, 51.20755272])

In [221]:
batched_magma_neg_likelihood = vmap(magma_neg_likelihood_new, in_axes=(task_kern.batch_in_axes, 0, 0, None, None, 0, None))
task_llhs_new = batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter)
np.asarray(task_llhs_new)

array([47.36790518, 48.19434489, 50.82895179, 46.73893308, 58.35595581,
       53.97453623, 50.98050792, 46.6903078 , 49.99814406, 55.66992366,
       46.08494662, 53.17678346, 45.49733488, 54.75629848, 50.89977383,
       50.36314154, 57.20056399, 51.89880572, 52.64762765, 51.20755272])

In [222]:
jnp.allclose(task_llhs_old, task_llhs_new)

Array(True, dtype=bool)

In [223]:
%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter).block_until_ready()

176 μs ± 916 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [224]:
%timeit batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_mean, post_cov, mappings, jitter).block_until_ready()

336 μs ± 1.41 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


---

### MagmaClust scenarios

We batch the hyperpost function so that it returns `post_mean` of shape `(K, N)` and `post_cov` of shape `(K, N, N)`

Depending on the scenario, we have to batch task kernels differently.

`fully shared HP` = `shared_hp` & `! cluster_hp`

`shared HP in cluster` = `shared_hp` & `cluster_hp`

`fully distinct HP` = `! shared_hp` & `! cluster_hp`

`distinct HP in cluster` = `! shared_hp` & `cluster_hp`

In this section, we only use **distinct inputs datasets** and focus only on **task likelihoods**.

#### Shared HP + no Cluster HP

- Each task has 1 set of HPs, optimised on the whole dataset
- They are optimised to maximise the likelihood of _**all**_ tasks, with respect to **_all_** clusters.

In [225]:
db = pd.read_csv(f"../datasets/K={nb_cluster}/{test_db_size}_distinct_input_shared_hp.csv")
padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)
prior_mean = jnp.array(0.)
prior_mean_on_grid = jnp.full(all_inputs.squeeze().shape, 0)
all_inputs.shape, padded_inputs.shape

((41, 1), (20, 20, 1))

In [226]:
mean_kern = SEMagmaKernel(length_scale=.1, variance=1.)
task_kern = SEMagmaKernel(length_scale=.2, variance=1.) + DiagKernel(ExpKernel(2.5))
task_kern = BatchKernel(task_kern, batch_size=padded_inputs.shape[0], batch_in_axes=None, batch_over_inputs=True)  # Batch along tasks

In [227]:
shared_input = len(padded_inputs[0]) == len(all_inputs) and not jnp.any(jnp.isnan(padded_inputs))
shared_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.batch_in_axes))
cluster_hp = False

shared_input, shared_hp, cluster_hp

(False, True, False)

In [228]:
init_mixture = k_means_init(padded_outputs, k=nb_cluster, distinct_hp=not shared_hp)
init_mixture.shape

(4, 20)

In [229]:
batched_hyperpost = vmap(hyperpost, in_axes=(None, None, None, None, None, None, None, None, None, 0))

In [230]:
post_means, post_covs = batched_hyperpost(
	padded_inputs, padded_outputs, mappings, all_inputs,
	prior_mean, mean_kern, task_kern,
	shared_input, shared_hp, init_mixture)
post_means.shape, post_covs.shape

((4, 41), (4, 41, 41))

In [231]:
# TODO: previous API wasn't compatible with batching. Replace when migration is done.
#task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)
#np.asarray(task_llhs_old)

In [232]:
task_batched_magma_neg_likelihood = vmap(magma_neg_likelihood_new, in_axes=(None, 0, 0, None, None, 0, None))
cluster_batched_magma_neg_likelihood = vmap(task_batched_magma_neg_likelihood, in_axes=(None, None, None, 0, 0, None, None))
task_llhs_new = cluster_batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_means, post_covs, mappings, jitter)
np.asarray(task_llhs_new)

array([[ 514.14941364,  690.67878432,  503.12246714,  534.49350884,
         515.36874314,  135.29891585,   84.39724411,  119.38184833,
         103.88613348,  136.42196632,  621.8277268 ,  734.94101914,
         654.06040766,  678.35922404,  770.27423183,  415.01339698,
         578.0843088 ,  419.89174493,  440.80720822,  468.3135601 ],
       [ 189.53023919,  232.18795316,  172.98848984,  169.5418439 ,
         181.45309755,  189.89484809,  168.06537783,  192.16449587,
         179.15214939,  208.89701172, 1069.07795001, 1304.62112771,
        1047.48876043, 1106.23538163, 1316.25220867,  563.39421578,
         623.92294107,  505.60981667,  555.90178509,  592.86108911],
       [1620.88050338, 1988.17311715, 1684.74863429, 1666.07008795,
        1629.68872276,  913.07612214,  687.13520765,  863.2971615 ,
         821.00294811,  908.04664008,   71.0593558 ,   97.57279298,
          71.82161687,   82.55013643,   85.55758319,  251.27988589,
         275.86265222,  231.33669234,  277.235

In [233]:
# Compare likelihood values of task to the initial mixture
print(f"{jnp.count_nonzero(init_mixture == jnp.eye(post_means.shape[0])[jnp.argmin(task_llhs_new, axis=0)].T).item()/len(init_mixture.ravel())*100:.2f}% agreement")

100.00% agreement


In [234]:
#jnp.allclose(task_llhs_old, task_llhs_new)

In [235]:
#%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)[0].block_until_ready()

In [236]:
%timeit cluster_batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_means, post_covs, mappings, jitter).block_until_ready()

1.67 ms ± 121 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Shared HP + Cluster HP

* Each task has K sets of HPs
* These K sets of HPs are shared among all tasks
* They are optimised to maximise the likelihood of **_all_** tasks (weighted by mixture coefficients), with respect to **_each_** cluster

In [237]:
db = pd.read_csv(f"../datasets/K={nb_cluster}/{test_db_size}_distinct_input_shared_hp.csv")
padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)
prior_mean = jnp.array(0.)
prior_mean_on_grid = jnp.full(all_inputs.squeeze().shape, 0)
all_inputs.shape, padded_inputs.shape

((41, 1), (20, 20, 1))

In [238]:
mean_kern = SEMagmaKernel(length_scale=.1, variance=1.)
task_kern = SEMagmaKernel(length_scale=.2, variance=1.) + DiagKernel(ExpKernel(2.5))
task_kern = BatchKernel(task_kern, batch_size=padded_inputs.shape[0], batch_in_axes=None, batch_over_inputs=True)  # Batch along tasks
task_kern = BatchKernel(task_kern, batch_size=nb_cluster, batch_in_axes=0, batch_over_inputs=False)  # Batch along clusters

In [239]:
shared_input = len(padded_inputs[0]) == len(all_inputs) and not jnp.any(jnp.isnan(padded_inputs))
shared_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.inner_kernel.batch_in_axes))
cluster_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.batch_in_axes))

shared_input, shared_hp, cluster_hp

(False, True, False)

In [240]:
init_mixture = k_means_init(padded_outputs, k=nb_cluster, distinct_hp=not shared_hp)
init_mixture.shape

(4, 20)

In [241]:
batched_hyperpost = vmap(hyperpost, in_axes=(None, None, None, None, None, None, task_kern.batch_in_axes, None, None, 0))

In [242]:
post_means, post_covs = batched_hyperpost(
	padded_inputs, padded_outputs, mappings, all_inputs,
	prior_mean, mean_kern, task_kern.inner_kernel,
	shared_input, shared_hp, init_mixture)
post_means.shape, post_covs.shape

((4, 41), (4, 41, 41))

In [243]:
# TODO: previous API wasn't compatible with batching. Replace when migration is done.
#task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)
#np.asarray(task_llhs_old)

In [244]:
task_batched_magma_neg_likelihood = vmap(magma_neg_likelihood_new, in_axes=(None, 0, 0, None, None, 0, None))
cluster_batched_magma_neg_likelihood = vmap(lambda k, *args: task_batched_magma_neg_likelihood(k.inner_kernel, *args), in_axes=(0, None, None, 0, 0, None, None))
task_llhs_new = cluster_batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_means, post_covs, mappings, jitter)
np.asarray(task_llhs_new)

array([[ 514.14941364,  690.67878432,  503.12246714,  534.49350884,
         515.36874314,  135.29891585,   84.39724411,  119.38184833,
         103.88613348,  136.42196632,  621.8277268 ,  734.94101914,
         654.06040766,  678.35922404,  770.27423183,  415.01339698,
         578.0843088 ,  419.89174493,  440.80720822,  468.3135601 ],
       [ 189.53023919,  232.18795316,  172.98848984,  169.5418439 ,
         181.45309755,  189.89484809,  168.06537783,  192.16449587,
         179.15214939,  208.89701172, 1069.07795001, 1304.62112771,
        1047.48876043, 1106.23538163, 1316.25220867,  563.39421578,
         623.92294107,  505.60981667,  555.90178509,  592.86108911],
       [1060.53202055, 1258.51750291, 1035.77191648, 1077.01817027,
        1057.97739494,  643.92416629,  433.07337544,  625.72965969,
         553.74005198,  671.59885499,  239.05201567,  340.83722561,
         222.55949804,  261.32209288,  291.24370539,   69.24400869,
          94.54518579,   73.87163362,   76.843

In [245]:
# Compare likelihood values of task to the initial mixture
print(f"{jnp.count_nonzero(init_mixture == jnp.eye(post_means.shape[0])[jnp.argmin(task_llhs_new, axis=0)].T).item()/len(init_mixture.ravel())*100:.2f}% agreement")

100.00% agreement


In [246]:
#jnp.allclose(task_llhs_old, task_llhs_new)

In [247]:
#%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)[0].block_until_ready()

In [248]:
%timeit cluster_batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_means, post_covs, mappings, jitter).block_until_ready()

700 μs ± 2.28 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### Distinct HP + no Cluster HP

* Each task has 1 set of HPs
* They are optimised to maximise the likelihood of _**each**_ task with respect to _**all**_ clusters (weighted by mixture coefficients)

In [249]:
db = pd.read_csv(f"../datasets/K={nb_cluster}/{test_db_size}_distinct_input_distinct_hp.csv")
padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)
prior_mean = jnp.array(0.)
prior_mean_on_grid = jnp.full(all_inputs.squeeze().shape, 0)
all_inputs.shape, padded_inputs.shape

((41, 1), (20, 20, 1))

In [250]:
mean_kern = SEMagmaKernel(length_scale=.1, variance=1.)
task_kern = SEMagmaKernel(length_scale=.2, variance=1.) + DiagKernel(ExpKernel(2.5))
task_kern = BatchKernel(task_kern, batch_size=padded_inputs.shape[0], batch_in_axes=0, batch_over_inputs=True)  # Batch along tasks

In [251]:
shared_input = len(padded_inputs[0]) == len(all_inputs) and not jnp.any(jnp.isnan(padded_inputs))
shared_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.batch_in_axes))
cluster_hp = False

shared_input, shared_hp, cluster_hp

(False, False, False)

In [252]:
init_mixture = k_means_init(padded_outputs, k=nb_cluster, distinct_hp=not shared_hp)
init_mixture.shape

(4, 20)

In [253]:
batched_hyperpost = vmap(hyperpost, in_axes=(None, None, None, None, None, None, None, None, None, 0))

In [254]:
post_means, post_covs = batched_hyperpost(
	padded_inputs, padded_outputs, mappings, all_inputs,
	prior_mean, mean_kern, task_kern,
	shared_input, shared_hp, init_mixture)
post_means.shape, post_covs.shape

((4, 41), (4, 41, 41))

In [255]:
# TODO: previous API wasn't compatible with batching. Replace when migration is done.
#task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)
#np.asarray(task_llhs_old)

In [256]:
task_batched_magma_neg_likelihood = vmap(magma_neg_likelihood_new, in_axes=(0, 0, 0, None, None, 0, None))
cluster_batched_magma_neg_likelihood = vmap(task_batched_magma_neg_likelihood, in_axes=(None, None, None, 0, 0, None, None))
task_llhs_new = cluster_batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_means, post_covs, mappings, jitter)
np.asarray(task_llhs_new)

array([[ 655.94986088,  549.25984875,  349.59553579,  526.0734839 ,
         549.44106063,  255.66767812,  314.52214313,  218.10532498,
         245.42037505,  278.98641234, 2529.11822427, 3173.9312723 ,
        3055.87027508, 2746.8311937 , 2156.23219138,  130.62859201,
         114.25148127,  148.86926545,  115.38937146,  153.69427129],
       [ 184.27883148,  158.27059259,  105.07501847,  181.73930684,
         158.50660415,  302.19703535,  266.82527316,  238.99677703,
         256.17447267,  308.78371252, 1553.98174476, 2113.23255381,
        1946.8023088 , 1695.82071983, 1268.4804677 ,  730.57185149,
         699.36691885,  769.8115926 ,  683.92623876,  746.92979538],
       [ 948.95732533, 1150.81869905,  945.38123294, 1241.01174632,
        1060.52898418, 1668.71700943, 1452.79180793, 1367.98133904,
        1513.65926664, 1712.48628913,  277.93082244,  422.96659235,
         393.02327568,  338.51394519,  252.31325757, 1790.59144913,
        1955.1861346 , 1991.95670453, 1810.394

In [257]:
# Compare likelihood values of task to the initial mixture
print(f"{jnp.count_nonzero(init_mixture == jnp.eye(post_means.shape[0])[jnp.argmin(task_llhs_new, axis=0)].T).item()/len(init_mixture.ravel())*100:.2f}% agreement")

90.00% agreement


In [258]:
#jnp.allclose(task_llhs_old, task_llhs_new)

In [259]:
#%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)[0].block_until_ready()

In [260]:
%timeit cluster_batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_means, post_covs, mappings, jitter).block_until_ready()

1.76 ms ± 169 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Distinct HP + Cluster HP

- Each task has K sets of HPs
- Each set is specific to the task
- They are optimised to maximise the likelihood of _**each**_ task with respect to _**each**_ cluster

In [261]:
db = pd.read_csv(f"../datasets/K={nb_cluster}/{test_db_size}_distinct_input_distinct_hp.csv")
padded_inputs, padded_outputs, mappings, all_inputs = preprocess_db(db)
prior_mean = jnp.array(0.)
prior_mean_on_grid = jnp.full(all_inputs.squeeze().shape, 0)
all_inputs.shape, padded_inputs.shape

((41, 1), (20, 20, 1))

In [262]:
mean_kern = SEMagmaKernel(length_scale=.1, variance=1.)
task_kern = SEMagmaKernel(length_scale=.2, variance=1.) + DiagKernel(ExpKernel(2.5))
task_kern = BatchKernel(task_kern, batch_size=padded_inputs.shape[0], batch_in_axes=0, batch_over_inputs=True)  # Batch along tasks
task_kern = BatchKernel(task_kern, batch_size=nb_cluster, batch_in_axes=0, batch_over_inputs=False)  # Batch along clusters

In [263]:
shared_input = len(padded_inputs[0]) == len(all_inputs) and not jnp.any(jnp.isnan(padded_inputs))
shared_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.inner_kernel.batch_in_axes))
cluster_hp = jax.tree.all(jax.tree.map(lambda x: x is None, task_kern.batch_in_axes))

shared_input, shared_hp, cluster_hp

(False, False, False)

In [264]:
init_mixture = k_means_init(padded_outputs, k=nb_cluster, distinct_hp=not shared_hp)
init_mixture.shape

(4, 20)

In [265]:
batched_hyperpost = vmap(hyperpost, in_axes=(None, None, None, None, None, None, task_kern.batch_in_axes, None, None, 0))

In [266]:
post_means, post_covs = batched_hyperpost(
	padded_inputs, padded_outputs, mappings, all_inputs,
	prior_mean, mean_kern, task_kern.inner_kernel,
	shared_input, shared_hp, init_mixture)
post_means.shape, post_covs.shape

((4, 41), (4, 41, 41))

In [267]:
# TODO: previous API wasn't compatible with batching. Replace when migration is done.
#task_llhs_old = magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)
#np.asarray(task_llhs_old)

In [268]:
task_batched_magma_neg_likelihood = vmap(magma_neg_likelihood_new, in_axes=(0, 0, 0, None, None, 0, None))
cluster_batched_magma_neg_likelihood = vmap(lambda k, *args: task_batched_magma_neg_likelihood(k.inner_kernel, *args), in_axes=(0, None, None, 0, 0, None, None))
task_llhs_new = cluster_batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_means, post_covs, mappings, jitter)
np.asarray(task_llhs_new)

array([[ 184.27883148,  158.27059259,  105.07501847,  181.73930684,
         158.50660415,  302.19703535,  266.82527316,  238.99677703,
         256.17447267,  308.78371252, 1553.98174476, 2113.23255381,
        1946.8023088 , 1695.82071983, 1268.4804677 ,  730.57185149,
         699.36691885,  769.8115926 ,  683.92623876,  746.92979538],
       [ 655.94986088,  549.25984875,  349.59553579,  526.0734839 ,
         549.44106063,  255.66767812,  314.52214313,  218.10532498,
         245.42037505,  278.98641234, 2529.11822427, 3173.9312723 ,
        3055.87027508, 2746.8311937 , 2156.23219138,  130.62859201,
         114.25148127,  148.86926545,  115.38937146,  153.69427129],
       [ 296.75085577,  212.18061217,  105.58317543,  243.05214868,
         228.05317787,  188.67549666,  190.33686309,  134.25625745,
         158.6955094 ,  197.10960525, 1925.27004891, 2540.47667212,
        2392.84418163, 2113.21804413, 1545.32095763,  440.3457568 ,
         407.3019678 ,  466.60032212,  423.827

In [269]:
# Compare likelihood values of task to the initial mixture
print(f"{jnp.count_nonzero(init_mixture == jnp.eye(post_means.shape[0])[jnp.argmin(task_llhs_new, axis=0)].T).item()/len(init_mixture.ravel())*100:.2f}% agreement")

90.00% agreement


In [270]:
#jnp.allclose(task_llhs_old, task_llhs_new)

In [271]:
#%timeit magma_neg_likelihood_old(task_kern, padded_inputs, padded_outputs, mappings, post_mean, post_cov, jitter=jitter)[0].block_until_ready()

In [272]:
%timeit cluster_batched_magma_neg_likelihood(task_kern.inner_kernel, padded_inputs, padded_outputs, post_means, post_covs, mappings, jitter).block_until_ready()

737 μs ± 3.07 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


---

## Conclusion

---